import type { ApiDefinition } from "./types.js";

function queryParam(name: string, required: boolean, description: string) {
  return { name, required, source: "query" as const, description };
}

function bodyParam(name: string, required: boolean, description: string) {
  return { name, required, source: "body" as const, description };
}

export const apiRegistry: ApiDefinition[] = [
  {
    apiName: "dp.merchant.name.search",
    title: "查询商家信息",
    group: "merchant",
    version: "v1",
    transport: "http",
    method: "POST",
    path: "/rest",
    riskLevel: "read",
    approvalRequired: false,
    callSyntax: "deepdraw call dp.merchant.name.search --param name=森马",
    semanticCommand: "deepdraw merchant search",
    requiredParams: [],
    optionalParams: [queryParam("name", false, "商户名称，支持模糊查询")],
    notes: "Returns merchant id, name, and brand data.",
  },
  {
    apiName: "dp.merchant.sites.get",
    title: "获取商户支持平台",
    group: "merchant",
    version: "v2",
    transport: "http",
    method: "GET",
    path: "/rest/v2",
    riskLevel: "read",
    approvalRequired: false,
    callSyntax: "deepdraw call dp.merchant.sites.get",
    semanticCommand: "deepdraw merchant sites",
    requiredParams: [queryParam("merchantId", true, "商户在深绘系统内的 id")],
    optionalParams: [],
    notes: "Reference requires merchantId; execution may source it from tenant config later.",
  },
  {
    apiName: "dp.merchant.watermarks.get",
    title: "查询水印信息",
    group: "merchant",
    version: "v2",
    transport: "http",
    method: "GET",
    path: "/rest/v2",
    riskLevel: "read",
    approvalRequired: false,
    callSyntax: "deepdraw call dp.merchant.watermarks.get",
    semanticCommand: "deepdraw merchant watermarks",
    requiredParams: [queryParam("merchantId", true, "商户在深绘系统内的 id")],
    optionalParams: [],
    notes: "Reference requires merchantId; execution may source it from tenant config later.",
  },
  {
    apiName: "dp.merchant.trades",
    title: "获取类目",
    group: "trade",
    version: "v1",
    transport: "http",
    method: "POST",
    path: "/rest",
    riskLevel: "read",
    approvalRequired: false,
    callSyntax: "deepdraw call dp.merchant.trades --param merchantId=MERCHANT_ID",
    semanticCommand: "deepdraw trade list",
    requiredParams: [queryParam("merchantId", true, "商户 id")],
    optionalParams: [],
    notes: "Category tree for tenant merchant.",
  },
  {
    apiName: "dp.trade.fields",
    title: "获取类目字段",
    group: "trade",
    version: "v1",
    transport: "http",
    method: "POST",
    path: "/rest",
    riskLevel: "read",
    approvalRequired: false,
    callSyntax: "deepdraw call dp.trade.fields --param merchantId=MERCHANT_ID --param tradeId=123",
    semanticCommand: "deepdraw trade fields",
    requiredParams: [queryParam("merchantId", true, "商户 id"), queryParam("tradeId", true, "深绘叶子类目 id")],
    optionalParams: [],
    notes: "Returns field definitions for a leaf category.",
  },
  {
    apiName: "dp.product.create",
    title: "创建产品",
    group: "product",
    version: "v1",
    transport: "java-sdk",
    method: "POST",
    path: "/rest",
    riskLevel: "write",
    approvalRequired: true,
    callSyntax: "deepdraw call dp.product.create --param merchantId=MERCHANT_ID --param tradeId=TRADE_ID --json-file product.json --plan",
    semanticCommand: "deepdraw product create",
    requiredParams: [
      queryParam("merchantId", true, "商户 id"),
      queryParam("tradeId", true, "深绘叶子类目 id"),
      bodyParam("product", true, "产品创建 payload"),
    ],
    optionalParams: [],
    notes: "Uses Java SDK bridge for entity mapping.",
  },
  {
    apiName: "dp.product.update",
    title: "更新产品",
    group: "product",
    version: "v1",
    transport: "java-sdk",
    method: "POST",
    path: "/rest",
    riskLevel: "write",
    approvalRequired: true,
    callSyntax: "deepdraw call dp.product.update --param productId=PRODUCT_ID --json-file product.json --plan",
    semanticCommand: "deepdraw product update",
    requiredParams: [queryParam("productId", true, "深绘产品 id"), bodyParam("product", true, "产品更新 payload")],
    optionalParams: [],
    notes: "Uses Java SDK bridge because update payload is an SDK entity.",
  },
  {
    apiName: "dp.product.incremental.update",
    title: "产品增量更新",
    group: "product",
    version: "v2",
    transport: "http",
    method: "POST",
    path: "/rest/v2",
    riskLevel: "write",
    approvalRequired: true,
    callSyntax: "deepdraw call dp.product.incremental.update --param productId=PRODUCT_ID --json-file patch.json --plan",
    semanticCommand: "deepdraw product patch",
    requiredParams: [queryParam("productId", true, "深绘产品 id"), bodyParam("product", true, "增量更新 payload")],
    optionalParams: [],
    notes: "Approval required because it mutates product data. Uses POST so JSON patch payloads can be sent consistently.",
  },
  {
    apiName: "dp.product.resource",
    title: "获取产品指定类型资源",
    group: "product",
    version: "v2",
    transport: "java-sdk",
    method: "GET",
    path: "/rest/v2",
    riskLevel: "read",
    approvalRequired: false,
    callSyntax: "deepdraw call dp.product.resource --param productCode=208226102001 --param resource=form",
    semanticCommand: "deepdraw product resource",
    requiredParams: [],
    optionalParams: [
      queryParam("productId", false, "产品在深绘系统内的 id"),
      queryParam("merchantId", false, "客户在深绘系统内的 id"),
      queryParam("productCode", false, "产品货号"),
      queryParam("resource", false, "资源类型：picture、detail、form、video；不填默认全部"),
      queryParam("wgId", false, "水印规则 id"),
      queryParam("skc", false, "产品 skc，多个用逗号分隔"),
      queryParam("material", false, "是否返回素材图信息，1 或 0，默认 0"),
      queryParam("video", false, "是否返回视频信息，1 或 0，默认 0"),
      queryParam("detailPageSite", false, "查询指定平台的详情页图"),
      queryParam("excludeDetailPageModules", false, "过滤指定详情页模块，多个用逗号分隔"),
    ],
    notes: "Uses Java SDK ProductGetByIdRequest for Listingify-compatible readback, with newer query filters preserved by the CLI bridge. The reference allows lookup by productId or by merchantId and productCode; if both are supplied, productId takes precedence.",
  },
  {
    apiName: "dp.product.search",
    title: "查询产品列表（慎用）",
    group: "product",
    version: "v2",
    transport: "http",
    method: "GET",
    path: "/rest/v2",
    riskLevel: "caution",
    approvalRequired: true,
    callSyntax: "deepdraw call dp.product.search --param merchantId=MERCHANT_ID --param productCodes=208226102001 --plan",
    semanticCommand: "deepdraw product search",
    requiredParams: [queryParam("merchantId", true, "商户 id")],
    optionalParams: [
      queryParam("date", false, "深绘内部定义的产品期数"),
      queryParam("pageNo", false, "页码，默认 1"),
      queryParam("startTime", false, "查询起始时间，毫秒"),
      queryParam("endTime", false, "查询结束时间，毫秒"),
      queryParam("form", false, "是否查询表单变化的产品，1 或 0，默认 0"),
      queryParam("picture", false, "是否查询资源图变化的产品，1 或 0，默认 0"),
      queryParam("detail", false, "是否查询详情页变化的产品，1 或 0，默认 0"),
      queryParam("productCodes", false, "货号，多个用逗号拼接"),
      queryParam("material", false, "是否返回素材图信息，1 或 0，默认 0"),
      queryParam("video", false, "是否返回视频信息，1 或 0，默认 0"),
      queryParam("excludeDraft", false, "是否排除草稿状态货号，1 或 0，默认 1"),
      queryParam("detailPageSite", false, "查询指定平台的详情页图"),
      queryParam("excludeDetailPageModules", false, "过滤指定详情页模块，多个用逗号分隔"),
    ],
    notes: "Reference marks this endpoint as caution; require plan confirmation.",
  },
  {
    apiName: "dp.feature.pictures.get",
    title: "获取商品指定类型素材/资源图原图",
    group: "product",
    version: "v2",
    transport: "http",
    method: "GET",
    path: "/rest/v2",
    riskLevel: "read",
    approvalRequired: false,
    callSyntax: "deepdraw call dp.feature.pictures.get --param productCode=208226102001 --param pictureType=MODEL",
    semanticCommand: "deepdraw product pictures",
    requiredParams: [queryParam("pictureType", true, "图片类型")],
    optionalParams: [
      queryParam("productId", false, "产品在深绘系统内的 id"),
      queryParam("merchantId", false, "客户在深绘系统内的 id"),
      queryParam("productCode", false, "产品货号"),
      queryParam("pictureSite", false, "图片平台，默认只查询素材图"),
      queryParam("width", false, "图片宽度，1-4096 范围内整数"),
      queryParam("body_facing", false, "主体朝向，仅适用模特图"),
      queryParam("body_part", false, "人体位置，仅适用模特图"),
      queryParam("body_orientation", false, "主体正反，仅适用挂拍图"),
      queryParam("skc", false, "产品 skc，多个用逗号分隔"),
    ],
    notes: "Supports resource picture filtering by platform. The reference allows lookup by productId or by merchantId and productCode; if both are supplied, productId takes precedence.",
  },
  {
    apiName: "dp.product.basic.search",
    title: "查询产品基础信息列表",
    group: "product",
    version: "v2",
    transport: "http",
    method: "GET",
    path: "/rest/v2",
    riskLevel: "read",
    approvalRequired: false,
    callSyntax: "deepdraw call dp.product.basic.search --param merchantId=MERCHANT_ID --param productCodes=208226102001",
    semanticCommand: "deepdraw product basic-search",
    requiredParams: [queryParam("merchantId", true, "商户 id")],
    optionalParams: [
      queryParam("date", false, "深绘内部定义的产品期数"),
      queryParam("pageNo", false, "页码，默认 1"),
      queryParam("pageSize", false, "分页大小，默认 20，最大 200"),
      queryParam("startTime", false, "查询起始时间，毫秒"),
      queryParam("endTime", false, "查询结束时间，毫秒"),
      queryParam("form", false, "是否查询表单变化的产品，1 或 0，默认 0"),
      queryParam("picture", false, "是否查询资源图变化的产品，1 或 0，默认 0"),
      queryParam("detail", false, "是否查询详情页变化的产品，1 或 0，默认 0"),
      queryParam("productCodes", false, "货号，多个用逗号拼接"),
      queryParam("excludeDraft", false, "是否排除草稿状态货号，1 或 0，默认 1"),
    ],
    notes: "Low-risk product lookup.",
  },
  {
    apiName: "dp.product.detail.get",
    title: "查询产品详情页",
    group: "product",
    version: "v1",
    transport: "http",
    method: "POST",
    path: "/rest",
    riskLevel: "read",
    approvalRequired: false,
    callSyntax: "deepdraw call dp.product.detail.get --param productId=PRODUCT_ID",
    semanticCommand: null,
    requiredParams: [queryParam("productId", true, "深绘产品 id")],
    optionalParams: [
      queryParam("quality", false, "详情页质量筛选"),
      queryParam("excludeDetailPageModules", false, "过滤指定详情页模块，多个用逗号分隔"),
    ],
    notes: "SDK class evidence: ProductPostFindDetailPageByIdRequest exposes productId, quality, setProductId(Long), and setQuality(String); reference update record adds excludeDetailPageModules.",
  },
  {
    apiName: "dp.product.distribution.get",
    title: "查询产品上架状态",
    group: "product",
    version: "v2",
    transport: "http",
    method: "GET",
    path: "/rest/v2",
    riskLevel: "read",
    approvalRequired: false,
    callSyntax: "deepdraw call dp.product.distribution.get --param productId=PRODUCT_ID",
    semanticCommand: "deepdraw product distribution",
    requiredParams: [queryParam("productId", true, "深绘产品 id")],
    optionalParams: [],
    notes: "Returns listing/distribution status.",
  },
  {
    apiName: "dp.product.retrieve.image",
    title: "以图搜款-款号接口",
    group: "image",
    version: "v2",
    transport: "http",
    method: "GET",
    path: "/rest/v2",
    riskLevel: "paid",
    approvalRequired: true,
    callSyntax: "deepdraw call dp.product.retrieve.image --param merchantId=MERCHANT_ID --param url=https://example.test/a.jpg --plan",
    semanticCommand: "deepdraw image retrieve",
    requiredParams: [queryParam("merchantId", true, "商户在深绘系统中的 id")],
    optionalParams: [
      queryParam("url", false, "图片地址"),
      queryParam("img", false, "图片 base64 编码"),
      queryParam("outline", false, "主体九宫格位置"),
    ],
    notes: "Reference marks this endpoint as extra charge. url and img are alternatives; one is required, and url takes precedence when both are supplied.",
  },
  {
    apiName: "dp.product.distributions.get",
    title: "以图搜款-查询上货记录",
    group: "image",
    version: "v2",
    transport: "http",
    method: "GET",
    path: "/rest/v2",
    riskLevel: "read",
    approvalRequired: false,
    callSyntax: "deepdraw call dp.product.distributions.get --param productId=PRODUCT_ID",
    semanticCommand: "deepdraw image distributions",
    requiredParams: [queryParam("productId", true, "产品在深绘系统内的 id")],
    optionalParams: [],
    notes: "Query image retrieval distribution records.",
  },
  {
    apiName: "dp.product.label.image",
    title: "图片服装多标签分析",
    group: "image",
    version: "v2",
    transport: "http",
    method: "GET",
    path: "/rest/v2",
    riskLevel: "paid",
    approvalRequired: true,
    callSyntax: "deepdraw call dp.product.label.image --param url=https://example.test/a.jpg --plan",
    semanticCommand: "deepdraw image label",
    requiredParams: [],
    optionalParams: [queryParam("url", false, "图片地址"), queryParam("img", false, "图片 base64 编码")],
    notes: "Reference marks this endpoint as extra charge. url and img are alternatives; one is required, and url takes precedence when both are supplied.",
  },
  {
    apiName: "dp.product.image.upload",
    title: "图片素材上传接口",
    group: "image",
    version: "v2",
    transport: "http",
    method: "POST",
    path: "/rest/v2",
    riskLevel: "paid_write",
    approvalRequired: true,
    callSyntax: "deepdraw call dp.product.image.upload --json-file upload.json --plan",
    semanticCommand: "deepdraw image upload",
    requiredParams: [
      queryParam("merchantId", true, "商户 ID"),
      queryParam("productId", true, "产品 ID"),
      bodyParam("images", true, "要上传的图片集合，不能大于 100 条"),
    ],
    optionalParams: [],
    notes: "Reference marks this endpoint as extra charge and it creates upload tasks. Uses POST so image upload JSON payloads can be sent consistently.",
  },
  {
    apiName: "dp.product.image.query",
    title: "查询上传图片素材任务接口",
    group: "image",
    version: "v2",
    transport: "http",
    method: "GET",
    path: "/rest/v2",
    riskLevel: "paid",
    approvalRequired: true,
    callSyntax: "deepdraw call dp.product.image.query --param taskId=TASK_ID",
    semanticCommand: "deepdraw image upload-status",
    requiredParams: [queryParam("taskId", true, "图片上传任务 id"), queryParam("merchantId", true, "商户 id")],
    optionalParams: [],
    notes: "Extra-charge image upload task status query; approval is required because the reference labels the endpoint as paid.",
  },
  {
    apiName: "dp.product.image.update",
    title: "图片修改",
    group: "image",
    version: "v2",
    transport: "http",
    method: "POST",
    path: "/rest/v2",
    riskLevel: "paid_write",
    approvalRequired: true,
    callSyntax: "deepdraw call dp.product.image.update --json-file update.json --plan",
    semanticCommand: "deepdraw image update",
    requiredParams: [
      queryParam("merchantId", true, "商户 ID"),
      bodyParam("images", true, "图片修改 payload，不能大于 100 条"),
    ],
    optionalParams: [
      queryParam("productId", false, "产品 ID"),
      queryParam("productCode", false, "产品货号"),
      queryParam("pictureAddType", false, "图片新增方式，默认 APPEND"),
    ],
    notes: "Reference marks this endpoint as extra charge and it mutates images. Uses POST so image update JSON payloads can be sent consistently. productId and productCode are alternatives; one must be supplied.",
  },
  {
    apiName: "dp.colors.get",
    title: "获取深绘标准颜色",
    group: "common",
    version: "v2",
    transport: "http",
    method: "GET",
    path: "/rest/v2",
    riskLevel: "read",
    approvalRequired: false,
    callSyntax: "deepdraw call dp.colors.get",
    semanticCommand: "deepdraw color list",
    requiredParams: [],
    optionalParams: [],
    notes: "Low-risk common metadata endpoint.",
  },
];

export function findApiDefinition(apiName: string): ApiDefinition | undefined {
  return apiRegistry.find((api) => api.apiName === apiName);
}
