"""Extract authorized local reference cells to a versioned TypeScript data module (no workbook edits)."""
import argparse, hashlib, json, re, zipfile, xml.etree.ElementTree as E
from pathlib import Path
N={'x':'http://schemas.openxmlformats.org/spreadsheetml/2006/main'}
def sheet(path,name):
 with zipfile.ZipFile(path) as z:
  strings=[''.join(t.text or '' for t in item.findall('.//x:t',N)) for item in E.fromstring(z.read('xl/sharedStrings.xml')).findall('x:si',N)] if 'xl/sharedStrings.xml' in z.namelist() else []
  relations={r.get('Id'):r.get('Target') for r in E.fromstring(z.read('xl/_rels/workbook.xml.rels'))}
  item=next(s for s in E.fromstring(z.read('xl/workbook.xml')).findall('x:sheets/x:sheet',N) if s.get('name')==name)
  target=relations[item.get('{http://schemas.openxmlformats.org/officeDocument/2006/relationships}id')]
  xml=target.lstrip('/') if target.startswith('/') else 'xl/'+target
  cells={}
  for c in E.fromstring(z.read(xml)).findall('.//x:sheetData/x:row/x:c',N):
   v=c.find('x:v',N); value=v.text or '' if v is not None else ''
   if c.get('t')=='s':value=strings[int(value)]
   elif c.get('t')=='inlineStr':value=''.join(t.text or '' for t in c.findall('.//x:t',N))
   cells[c.get('r')]=value
  return cells
p=argparse.ArgumentParser();p.add_argument('--apparel',required=True);p.add_argument('--shoe',required=True);p.add_argument('--output',default='src/brands/balabala/size-reference-data.ts');a=p.parse_args()
app=sheet(a.apparel,'balabala');shoe=sheet(a.shoe,'数据转化')
app_rows=[]
for r in range(2,19):
 values=[app.get(f'{c}{r}','') for c in ['B','C','D','F','G','H','I','J','K','L']]
 assert all(values) and re.fullmatch(r'\d+',values[0]),('invalid apparel reference',r)
 app_rows.append([int(values[0]),float(values[1]),values[2],float(values[3]),*values[4:]])
shoe_rows=[]
for r in sorted({int(re.sub('[A-Z]','',address)) for address in shoe}):
 v=lambda c:shoe.get(f'{c}{r}','')
 if not re.fullmatch(r'\d+',v('D')):continue
 row={'size':v('D'),'foot_length_mm':v('F'),'footRange':v('H'),'referenceAge':v('B'),'referenceStage':v('C'),'sourceRow':r}
 for prefix,cols in [('openSandal',['I','J','K','L','M']),('closedSandal',['N','O','P','Q','R']),('sport',['S','T','U','V','W'])]:
  row.update(dict(zip([prefix+'InnerLengthMm',prefix+'InnerLength',prefix+'Remark',prefix+'Douyin',prefix+'Vip'],map(v,cols))))
 row.update({'sportMulti':v('X'),'sportPdd':v('Y')})
 assert row['foot_length_mm'] and row['sportInnerLengthMm'],('invalid shoe reference',r)
 shoe_rows.append(row)
provenance={'version':'2026-09-08','apparel':{'file':Path(a.apparel).name,'sheet':'balabala','range':'A1:L18','sha256':hashlib.sha256(Path(a.apparel).read_bytes()).hexdigest()},'shoe':{'file':Path(a.shoe).name,'sheet':'数据转化','range':'A1:Y32','sha256':hashlib.sha256(Path(a.shoe).read_bytes()).hexdigest()},'scope':'Balabala apparel reference and integer shoe sizes only; Semir, mini Balabala and sock measurement tables are not applied to ordinary apparel.'}
Path(a.output).write_text('// Generated by scripts/internalize-size-references.py. Do not edit cells by hand.\nexport const SIZE_REFERENCE_SOURCE = '+json.dumps(provenance,ensure_ascii=False,indent=2)+' as const;\nexport const BUILTIN_APPAREL_ROWS = '+json.dumps(app_rows,ensure_ascii=False,indent=2)+' as const;\nexport const BUILTIN_SHOE_ROWS = '+json.dumps(shoe_rows,ensure_ascii=False,indent=2)+' as const;\n')
print(json.dumps({'apparelRows':len(app_rows),'shoeRows':len(shoe_rows),'source':provenance},ensure_ascii=False))
